# Generated by Django 3.2 on 2022-08-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'UserAuthentication',
            },
        ),
    ]
